accounts/urls.py
from django.urls import path
from .views import homepage, profile, login, create_account, dashboard, GetFactoriesView, create_buyer_account, create_seller_account, logout

namespace = "accounts"

urlpatterns = [
    path("", homepage, name="homepage"),
    path("profile/", profile, name="profile"),
    path("login/", login, name="login"),
    path("dashboard/", dashboard, name="dashboard"),
    path("factories/", GetFactoriesView.as_view(), name="factories"),
    path('create_account/', create_account, name= "create_account"),
    path('create_buyer_account/', create_buyer_account, name = 'create_buyer_account'),
    path('create_seller_account/', create_seller_account, name = 'create_seller_account'),
    path("logout/", logout, name = "logout")
]

agriproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

namespace = "transactions"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path(
        "transactions/",
        include(("transactions.urls", "transactions"), namespace="transactions"),
    ),
    path("feedback/", include(("feedback.urls", "feedback"), namespace="feedback")),
    path("blog/", include(("blog.urls", "blog"), namespace = "blog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import blog, blog_single

urlpatterns = [
    path('', blog , name = 'blog'),
    path('<int:id>/', blog_single, name = "blog_single")
]

transactions/urls.py
from django.urls import path
from .views import (
    add_auction,
    view_market,
    view_market_id,
    view_order,
    view_auction,
    chat,
    view_factory,
    AcceptOrderView,
    EnterShipmentInfoView,
    AddShipmentAddressView,
    GetChartView,
    confirmArival,
    DeletAuction,
    CreateAuction,
    GetBuyerChartView,
    ShowAuctionHistory,
    ShowTransactions,
)

namespace = "transactions"

urlpatterns = [
    path("add_auction/", add_auction, name="add_auction"),
    path("view_market/", view_market, name="view_market"),
    path("view_market/<int:id>/", view_market_id, name="view_market"),
    path("view_order/<int:order_id>/", view_order, name="view_order"),
    path("view_auction/", view_auction, name="view_auction"),
    path("chat/", chat, name="chat"),
    path(
        "view_market/view_factory/<int:factory_id>/", view_factory, name="view_factory"
    ),
    path(
        "view_order/<int:factory_id>/update_order/",
        AcceptOrderView.as_view(),
        name="accept_order",
    ),
    path(
        "shipmentinfo/<int:order_id>/",
        EnterShipmentInfoView.as_view(),
        name="shipmentview",
    ),
    path("ShipmentSaved/", EnterShipmentInfoView.as_view(), name="saveshipment"),
    path(
        "ShipmentAddress/",
        AddShipmentAddressView.as_view(),
        name="addshippmentaddress",
    ),
    path("charts/<str:factory_name>", GetChartView.as_view(), name="charts"),
    path("bcharts/<str:buyer_name>", GetBuyerChartView.as_view(), name="bcharts"),
    path("order-arrived/<int:order_id>", confirmArival, name="confirm"),
    path(
        "auction-remove/<int:auction_id>", DeletAuction.as_view(), name="delete-auction"
    ),
    path("create_auction/", CreateAuction.as_view(), name="create_auction"),
    path(
        "auction_history/<str:factory_name>/",
        ShowAuctionHistory.as_view(),
        name="auction_history",
    ),
    path("<str:factory_name>/", ShowTransactions.as_view(), name="showtransactions",),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User as user_model

User = user_model


class SellerFactory(models.Model):
    date_created = models.DateField(auto_now_add=True, null=True)
    factory_name = models.CharField(max_length=30)
    company_email = models.EmailField()
    phone = models.CharField(max_length=20)
    region = models.CharField(max_length=30)
    country = models.CharField(max_length=30)
    trade_license = models.FileField(null=True, blank=True)
    rating = models.IntegerField(null=True)
    factory_logo = models.ImageField(null=True)
    googlemap = models.TextField(null=True)
    factory_bio = models.TextField(default="No bio")

    def __str__(self):
        return self.factory_name


class SellerFactoryEmployee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    factory = models.ForeignKey(SellerFactory, on_delete = models.CASCADE)
    country = models.CharField(max_length = 30 , null = True)
    address = models.TextField(null = True)
    profile_picture = models.ImageField(null = True)
    phone = models.IntegerField(null = True)

    def __str__(self):
        return self.user.username


class Buyer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(max_length = 30, null = True)
    address = models.TextField(null = True)
    profile_picture = models.ImageField(null = True)
    phone = models.IntegerField(null = True)
    use_case = models.TextField(null = True)

    def __str__(self):
        return self.user.username

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import login as login_user, logout, authenticate
from django.contrib.auth.models import User
from transactions import calenderutil
from django.shortcuts import redirect
from .models import SellerFactoryEmployee, SellerFactory, Buyer
from django.views.generic import View
from django.urls import reverse
from transactions.models import Order, Auction


def homepage(request):
    return render(request, "homepage.html", {})


def profile(request):
    return render(request, "profile.html", {})


def logout(request):
    return redirect("accounts:homepage")

def login(request):
    error = None
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("pass")
        try:
            user = User.objects.get(email=email)
            if user.check_password(password) == True:
                login_user(request, user)
                return redirect("accounts:dashboard")
        except User.DoesNotExist:
            error = "incorrect email or password"
    return render(request, "login.html", {"error": error})


def dashboard(request):
    if request.user.is_authenticated:
        user = request.user
    else:
        return redirect("account:login")
    context = {"user": user}
    try:
        print(user.sellerfactoryemployee.factory)
        order_queryset = Order.objects.filter(employee=user.sellerfactoryemployee)
        auctions = Auction.objects.filter(factory=user.sellerfactoryemployee.factory)
        n = 0
        for order in order_queryset:
            if order.auction == auctions[0]:
                n += 1
        auctions = Auction.objects.all()
        prices = []
        months_price = []
        months = []
        for auction in auctions:
            price = auction.price_per_tonne
            months_price.append(auction.date)
            prices.append(price)
        sumprice = sum(prices)
        months = calenderutil.getAllMonthsStr()
        try:
            mean_price = sumprice / len(prices)
        except:
            mean_price = 0
        context = {
            "prices": prices,
            "months_price": months_price,
            "months": months,
            "MeanPrice": round(mean_price, 3),
        }

        context["auctions"] = auctions
        context["orders"] = n
        context["order_queryset"] = order_queryset

        print(context)
        return render(request, "seller_dashboard.html", context)
    except AttributeError:
        order_queryset = Order.objects.filter(buyer=user.buyer)
        auctions = []
        for order in order_queryset:
            auction = order.auction
            if auction not in auctions:
                auctions.append(auction)
        notifications = []
        for order in order_queryset:
            if order.status == 1 and not order.shipping_address:
                notification = Notification(
                    1,
                    "view_order",
                    f"Your Order for the {order.auction} has been accepted",
                    order.id,
                    "transactions",
                )
                notifications.append(notification)
        auctions = Auction.objects.all()
        prices = []
        months_price = []
        months = []
        for auction in auctions:
            price = auction.price_per_tonne
            months_price.append(auction.date)
            prices.append(price)
        sumprice = sum(prices)
        months = calenderutil.getAllMonthsStr()
        try:
            mean_price = sumprice / len(prices)
        except:
            mean_price = 0
        context = {
            "prices": prices,
            "months_price": months_price,
            "months": months,
            "MeanPrice": round(mean_price, 3),
        }
        context["notifycount"] = len(notifications)

        context["auctions"] = auctions
        context["order_queryset"] = order_queryset

        context["notifications"] = notifications

        orders = Order.objects.filter(buyer=user.buyer)
        context["orders"] = len(orders)
        context["pending"] = len(Order.objects.filter(buyer=user.buyer, status=0))
        context["confirmed"] = len(Order.objects.filter(buyer=user.buyer, status=1))
        context["processed"] = len(Order.objects.filter(buyer=user.buyer, status=2))
        context["completed"] = len(Order.objects.filter(buyer=user.buyer, status=3))
        factories = []
        for order in order_queryset:
            if order.employee.factory not in factories:
                factories.append(order.employee.factory)
        context["factories"] = factories
        return render(request, "buyer_dashboard.html", context)



class Notification:
    def __init__(self, type, action, messsage, id, app_name):
        self.type = type
        self.action = action
        self.message = messsage
        self.id = id
        self.app_name = app_name


class GetFactoriesView(View):
    def get(self, request, *args, **kwargs):
        context = {"factories": SellerFactory.objects.all()}
        return render(request, "factories.html", context)

def create_account(request):
    logout(request)
    return render(request, "create_account.html", {})

def create_buyer_account(request):
    if request.method == "POST":
        print(request.POST)
        if request.POST['username'] and request.POST['email'] and request.POST['pass'] and request.POST['repeatpass'] and request.POST['country'] and request.POST['address'] and request.POST['phone']:
            print("they all came in ")
            email = request.POST['email']
            username = request.POST['username']
            password = request.POST['pass']
            repeat_password = request.POST['repeatpass']
            country = request.POST['country']
            phone = request.POST['phone']
            address = request.POST['address']
            profile_photo = request.POST['profilepicture']
            email_queryset = User.objects.filter(email = email)
            if email_queryset.__len__() == 0:
                if password == repeat_password:
                    user = User.objects.create(username = username, email = email)
                    user.set_password(password)
                    user.save()
                    buyer = Buyer.objects.create(user = user ,country = country, address = address, profile_picture = profile_photo, phone = phone)
                    buyer.save()
                    return render(request, 'account_success.html', {})
                else:
                    print('passwords do not match')
            else:
                print("a user with that email already exists")
            

    return render(request, 'create_buyer_account.html', {})

def create_seller_account(request):
    if request.method == "POST":
        if request.POST['factoryphone'] and request.POST['factoryemail'] and request.POST['factoryname'] and request.POST['tradelicense'] and request.POST["factorylogo"] and request.POST['username'] and request.POST['email'] and request.POST['pass'] and request.POST['repeatpass'] and request.POST['country'] and request.POST['address'] and request.POST['phone']:
            if request.POST['pass'] == request.POST['repeatpass']:
                factory = SellerFactory.objects.create(factory_name = request.POST['factoryname'], factory_email=request.POST['factoryemail'], phone = request.POST['factoryphone'], country = request.POST['country'], trade_license = request.POST['tradelicense'], factory_logo = request.POST['factorylogo'])
                email = request.POST['email']
                username = request.POST['username']
                password = request.POST['pass']
                repeat_password = request.POST['repeatpass']
                country = request.POST['country']
                phone = request.POST['phone']
                address = request.POST['address']
                profile_photo = request.POST['profilepicture']
                email_queryset = User.objects.filter(email = email)
                company_email_queryset = SellerFactory.objects.filter(factory_email = email)
                if email_queryset.__len__() == 0 and company_email_queryset.__len__() == 0:
                    if password == repeat_password:
                        user = User.objects.create(username = username, email = email)
                        user.set_password(password)
                        user.save()
                        SellerFactoryEmployee.objects.create(factory = factory, user = user, country = country, address = address, profile_picture = profile_photo, phone = phone)
                        return render(request, 'account_success.html', {})
                    else:
                        print('passwords do not match')
                else:
                    print("a user with that email already exists")
            else:
                print("passwords do not match")
    return render(request, "create_seller_account.html", {})

accounts/templates/account_success.html
the account was created successfully

accounts/templates/account_type.html
{% include 'base.html' %} {% block content %}
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <!-- OVERVIEW -->
      <div class="panel panel-headline">
        <div class="row">
          <div class="col-md-7">this should at the center</div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

accounts/templates/buyer_dashboard.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'toastr/toastr.min.css' %}">
<link rel="stylesheet" href="{% static 'assets/css/mine.css'%}">
{% endblock style %}
{% block content %} {% load static %}
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <!-- OVERVIEW -->
      <div class="panel-body dark-l orange-border">
        <div class="panel-body">
          <h1 class="orange livetext-mega">Coffee Prices</h1>
          <h3 class="white">${{MeanPrice}} Per Tonne</h3>
          <p>Coffee prices in the market</p>
          <canvas id="prices" height="100"></canvas>
        </div>
      </div><br>
      <div class="row">
        <div class="col-md-12">
        </div>
      </div>
      <div class="dark orange-border panel-body">
        <h2 class="orange livetext-mega">suggested factories</h2>
        {%for factory in factories%}
        <div class="panel-body dark-l selector-dark">
          <img src="{{factory.factory_logo.url}}" alt="logo" class="img-circle"
            style="width: 80px; height: 80px; margin-right:10px; float: left;">
          <a href="{%url 'transactions:view_factory' factory.pk%}" class="white">{{factory.factory_name}}</a>
          <div class="dark">
            <span>{{factory.country}}</span>|
            <span>{{factory.region}}</span><br>
          </div>
          <span>
            {%if factory.rating == 0%}
            rating: Low
            {%elif factory.rating == 1%}
            rating: fair
            {%elif factory.rating == 2%}
            rating: good
            {%else%}
            rating: platinum
            {%endif%}
          </span>
        </div><br>
        {%endfor%}

        <a href="{% url 'accounts:factories'%}" class="btn btn-success">Show All factories</a>
      </div>
      <div class="row">
        <div class="col-md-12">
          <!-- RECENT PURCHASES -->
          <div class="dark-l panel-body orange-border">
            <div class="panel-heading">
              <h3 class="orange livetext-mega">Recent Transactions</h3>
              <div class="right">
                </button>
              </div>
            </div>
            <div class="panel-body no-padding">
              <table class="table ">
                <thead>
                  <tr>
                    <th class="small">Order No.</th>
                    <th class="small">Name</th>
                    <th class="small">Amount</th>
                    <th class="small">Date &amp; Time</th>
                    <th class="small">Status</th>
                    <th class="small">Transaction Validity</th>
                    <th class="small">Transaction Hash</th>
                  </tr>
                </thead>
                <tbody>
                  {% for order in order_queryset %}
                  <tr>
                    <td><a href="/transactions/view_order/{{order.id}}/">{{order.id}}</a></td>
                    <td>{{order.employee.factory.factory_name}}</td>
                    <td>{{order.amount}} tonnes</td>
                    <td>{{order.date_placed}}</td>
                    {% if order.status == 0 %}
                    <td class="small"><span class="label label-warning">Pending</span></td>
                    {% elif order.status == 1 %}
                    <td class="small"><span class="label label-success">Accepted</span></td>
                    {% elif order.status == 2 %}
                    <td class="small"><span class="label label-success">Processed</span></td>
                    {% elif order.status == 3 %}
                    <td class="small"><span class="label label-success">Completed</span></td>
                    {% endif %}
                    {%if order.chain_valid%}
                    <td class="small">
                      <span class="label-success label">Trusted</span>
                    </td>
                    {%else%}
                    <td class="small">
                      <span class="label-error label">Suspicius</span>
                    </td>
                    {%endif%}

                    <td>
                      <small class="no-padding no-margin">{{order.order_hash}}</small>
                    </td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="panel-body dark">
              <div class="row">
                <div class="col-md-6">
                  <span class="panel-note"><i class="fa fa-clock-o"></i> Last 24 hours</span>
                </div>
              </div>
            </div>
          </div>
          <!-- END RECENT PURCHASES -->

        </div>
      </div><br> <br>
      <div class="panel-body dark-l orange-border">
        <div class="metric dark">
          <h4 class="orange">Orders Placed</h4>
          <div class="panel-body"><span class="white">{{orders}} order(s)</span><br></div>
          <hr>
          <div class="dark-l panel-body"><span class="white">{{pending}} pending</span><br></div><br>
          <div class="dark-l panel-body"><span class="white">{{confirmed}} Accepted</span><br></div><br>
          <div class="dark-l panel-body"><span class="white">{{processed}} processed</span><br></div><br>
          <div class="dark-l panel-body"><span class="white">
              <span class="dot bg-success"></span>
              <span>
                {{completed}}
                Completed
              </span>
          </div>
        </div>
      </div><br>
      <div class="metric dark">
        <h4 class="white">Actions</h4>
        <a href="#">View all Transactions</a><br>
        <a href="#">View all Accepted transactions</a><br>
        <a href="#">Notifications</a>
        <hr>
        <h4 class="white">Common</h4>
        <a href="#">Print Transaction report</a><br>
        <a href="#">Trace order</a><br>
        <a href="#">Blog</a><br>
        <a href="#">Feedback</a>
      </div>
    </div>
    <br>

    <!-- END OVERVIEW -->
  </div>
</div>
</div>
</div>
<!-- END MAIN CONTENT -->
</div>
{% endblock content %}
{% block js %}
<script src="{%static 'node_modules/chart.js/dist/Chart.js'%}"></script>
<script>
  months = []
  prices = []
  factories = []
  amounts = []
</script>
{%for month in months_price%}
<script>
  included = false
  months.forEach(element =>
  {
    if (element === "{{month}}")
    {
      included = true
    }
  });
  if (!included)
  {

    months.push("{{month}}")
  }
</script>
{%endfor%}
{%for price in prices%}
<script>
  prices.push("{{price}}")
</script>
{%endfor%}
<script src="{% static 'toastr/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'toastr/toastr.min.js' %}"></script>
<script>
  var notificationSocket = new WebSocket(
    "ws://" + window.location.host + "/ws/transactions/notifications/{{user.id}}/"
  );
  notificationSocket.onmessage = function (e)
  {
    var receivedMessage = JSON.parse(e.data);

    toastr.options = {
      "closeButton": true,
      "debug": false,
      "newestOnTop": false,
      "progressBar": false,
      "positionClass": "toast-top-right",
      "preventDuplicates": false,
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "1000",
      "timeOut": "5000",
      "extendedTimeOut": "1000",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }

    toastr["info"](receivedMessage['content'], "new message received from " + receivedMessage['username'] +
      ' order number ' + receivedMessage['order_id'])

  }

  var ctx = document.getElementById('prices').getContext('2d');
  months.push("")
  var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: months,
      datasets: [{
        label: 'Price line in real time',
        data: prices,
        backgroundColor: [
          'rgba(100,100,100,0.2)',
        ],
        borderColor: [
          'rgba(226, 109, 6, 1)'
        ],
        borderWidth: 3
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: false
          }
        }]
      }
    }
  });
</script>
{% endblock js %}

accounts/templates/create_account.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Dashboard | Klorofil - Free Bootstrap Dashboard Template</title>
    <!-- chat stuff -->
    {% block style %} {% endblock style %}
    <!-- chat stuff -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    />
    <!-- VENDOR CSS -->
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/linearicons/style.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/chartist/css/chartist-custom.css' %}"
    />
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}" />
    <!-- GOOGLE FONTS -->
    <link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700"
      rel="stylesheet"
    />
    <!-- ICONS -->
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href="assets/img/apple-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="96x96"
      href="{% static 'assets/img/favicon.png' %}"
    />
  </head>

  <body>
    <!-- WRAPPER -->
    <div id="wrapper">
      <!-- NAVBAR -->
      {% include 'navbar.html' %}{% include 'sidebar.html' %}
      <!-- main content -->

      <div class="main">
        <!-- MAIN CONTENT -->
        <div class="main-content">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-6">
                <center>
                  <div class="panel">
                    <div class="panel-heading">
                      <h3 class="panel-title">
                        <b>Create A seller/factory account</b>
                      </h3>
                    </div>
                    <div class="panel-body">
                      <img
                        style="margin: 20px;"
                        height="100px"
                        width="100px"
                        src="{% static 'custom_images/sellerfactory2.jpg' %}"
                      />
                      <p>
                        creating a seller/factory account will enable you to
                        register a factory and sell coffee within this platform
                      </p>
                    </div>
                    <div class="panel-footer">
                      <h5>
                        <a
                          href="{% url 'accounts:create_seller_account' %}"
                          class="btn btn-primary"
                          >create seller account</a
                        >
                      </h5>
                    </div>
                  </div>
                </center>
              </div>
              <div class="col-md-6">
                <center>
                  <div class="panel">
                    <div class="panel-heading">
                      <h3 class="panel-title">
                        <b>Create A buyer/imports account</b>
                      </h3>
                    </div>
                    <div class="panel-body">
                      <img
                        style="margin: 20px;"
                        height="100px"
                        width="100px"
                        src="{% static 'custom_images/userdummy.jpg' %}"
                      />
                      <p>
                        creating a buyer/imports account will enable you to view
                        the coffee market and buy coffee from this platform
                      </p>
                    </div>
                    <div class="panel-footer">
                      <h5>
                        <a
                          href="{% url 'accounts:create_buyer_account' %}"
                          class="btn btn-primary"
                          >create buyer account</a
                        >
                      </h5>
                    </div>
                  </div>
                </center>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- endmain -->
      <div class="clearfix"></div>
      <footer>
        <div class="container-fluid">
          <p class="copyright">
            Shared by <i class="fa fa-love"></i
            ><a href="https://bootstrapthemes.co">BootstrapThemes</a>
          </p>
        </div>
      </footer>
    </div>
    <!-- END WRAPPER -->
    <!-- Javascript -->

    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js' %}"></script>
    <script src="{% static 'assets/vendor/chartist/js/chartist.min.js' %}"></script>
    <script src="{% static 'assets/scripts/klorofil-common.js' %}"></script>
    {% block js %} {% endblock js %}
  </body>
</html>

accounts/templates/factories.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'toastr/toastr.min.css' %}">
{% endblock style %}
{% block content %} {% load static %}
<div class="main">
    <div class="main-content dark">
        <div class="container-fluid">
            <div class="panel-body">
                <span class="orange title">CoffeeAfrica|</span><span class="blue">Partners</span><br><br>
                {%for factory in factories%}
                <div class="panel-body dark-l orange-border">
                    <img src="{{factory.factory_logo.url}}" alt="logo" class="img-circle"
                        style="width: 80px; height: 80px; margin-right:10px; float: left;">
                    <a href="{%url 'transactions:view_factory' factory.pk%}"
                        class="white title livetext">{{factory.factory_name}}</a>
                    <div class="dark">
                        <span>{{factory.country}}</span>|
                        <span>{{factory.region}}</span><br>
                    </div>
                    <span>
                        {%if factory.rating == 0%}
                        rating: Low
                        {%elif factory.rating == 1%}
                        rating: fair
                        {%elif factory.rating == 2%}
                        rating: good
                        {%else%}
                        rating: platinum
                        {%endif%}
                    </span><br>
                    <span>Partner since {{factory.date_created}}</span>
                    <hr>
                    <span class="white">About Factory</span><br>
                    <span>{{factory.factory_bio}}</span><br>
                    <a href="#">Send Message</a>
                    <br>
                    <a href="#">Report</a>
                </div><br>
                {%endfor%}
            </div>
        </div>
    </div>
</div>
{%endblock content%}