agriproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

namespace = "transactions"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path(
        "transactions/",
        include(("transactions.urls", "transactions"), namespace="transactions"),
    ),
    path("feedback/", include(("feedback.urls", "feedback"), namespace="feedback")),
    path("blog/", include(("blog.urls", "blog"), namespace = "blog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import blog, blog_single

urlpatterns = [
    path('', blog , name = 'blog'),
    path('<int:id>/', blog_single, name = "blog_single")
]

transactions/urls.py
from django.urls import path
from .views import (
    add_auction,
    view_market,
    view_market_id,
    view_order,
    view_auction,
    chat,
    view_factory,
    AcceptOrderView,
    EnterShipmentInfoView,
    AddShipmentAddressView,
    GetChartView,
    confirmArival,
    DeletAuction,
    CreateAuction,
    GetBuyerChartView,
    ShowAuctionHistory,
    ShowTransactions,
)

namespace = "transactions"

urlpatterns = [
    path("add_auction/", add_auction, name="add_auction"),
    path("view_market/", view_market, name="view_market"),
    path("view_market/<int:id>/", view_market_id, name="view_market"),
    path("view_order/<int:order_id>/", view_order, name="view_order"),
    path("view_auction/", view_auction, name="view_auction"),
    path("chat/", chat, name="chat"),
    path(
        "view_market/view_factory/<int:factory_id>/", view_factory, name="view_factory"
    ),
    path(
        "view_order/<int:factory_id>/update_order/",
        AcceptOrderView.as_view(),
        name="accept_order",
    ),
    path(
        "shipmentinfo/<int:order_id>/",
        EnterShipmentInfoView.as_view(),
        name="shipmentview",
    ),
    path("ShipmentSaved/", EnterShipmentInfoView.as_view(), name="saveshipment"),
    path(
        "ShipmentAddress/",
        AddShipmentAddressView.as_view(),
        name="addshippmentaddress",
    ),
    path("charts/<str:factory_name>", GetChartView.as_view(), name="charts"),
    path("bcharts/<str:buyer_name>", GetBuyerChartView.as_view(), name="bcharts"),
    path("order-arrived/<int:order_id>", confirmArival, name="confirm"),
    path(
        "auction-remove/<int:auction_id>", DeletAuction.as_view(), name="delete-auction"
    ),
    path("create_auction/", CreateAuction.as_view(), name="create_auction"),
    path(
        "auction_history/<str:factory_name>/",
        ShowAuctionHistory.as_view(),
        name="auction_history",
    ),
    path("<str:factory_name>/", ShowTransactions.as_view(), name="showtransactions",),
]

transactions/forms.py
from django.forms import ModelForm
import django.forms as forms
from django import forms as Nforms
from .models import Order, Auction
from django.db import models as db_models
from django.contrib.admin.widgets import AdminDateWidget


class ShipmentInfoForm(ModelForm):
    class Meta:
        model = Order
        fields = [
            "shipment_id",
            "vessel_number",
            "shipment_company",
            "estimated_time_on_ship",
            "time_of_shipping",
            "shipment_handler_phone",
        ]

        widgets = {
            "shipment_id": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter Shipment ID"}
            ),
            "shipment_company": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter Shipment Company name",
                }
            ),
            "vessel_number": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter Vessel Number"}
            ),
            "estimated_time_on_ship": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter Estimated Time on ship",
                }
            ),
            "shipment_handler_phone": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Phone"}
            ),
            "time_of_shipping": AdminDateWidget(
                attrs={
                    "placeholder": ("enter Date e.g 1999-1-4 yyyy-mm-dd"),
                    "class": "form-control",
                }
            ),
        }


class CreateAuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = [
            "tonnes",
            "price_per_tonne",
            "date_harvested",
            "bean_size",
            "status",
            "tempreture",
            "humidity",
            "soil_ph",
            "description",
        ]

        widgets = [[]]

transactions/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from .models import Auction, Order, Chat
from backup.models import BackAuction, BackOrder
from backup import backup_utils
import calendar
import dateutil
from . import calenderutil
try:
    from ..blockSys import intergrator
except:
    from blockSys import intergrator, utils

from accounts.models import SellerFactory
from accounts.models import SellerFactoryEmployee
from accounts.models import Buyer
from blockSys import *
from hashlib import sha256
from . import forms
from django.views.generic import View
from django.contrib.auth.models import User
import datetime
import time
from .forms import CreateAuctionForm
import json


def add_auction(request):
    form = CreateAuctionForm()
    # if request.method == 'POST':
    #     if request.POST['pass']:
    #         print('password came in')
    #         return render(request, 'add_auction.html')
    # return render(request, 'confirm_password.html', {})
    return render(request, "add_auction.html", context={'form':form})

def confirmArival(request, order_id):
    if request.method == 'GET':
        order = Order.objects.get(pk=order_id)
        order.arrived = True
        order.status = 3
        chain = intergrator.ReadChainFromFile(order_id)
        chain.addTochain(order)

        order.chain = chain.blockchain.getChainList()
        hasher = sha256(str(order.chain).encode('utf-8'))

        order.hash = hasher.hexdigest()
        order.chain_valid = chain.CheckValidity()

        chain.DumpChain(order_id)
        order.save()
        backup_utils.BackOrder(order)
        return HttpResponse("Updated")

class GetBuyerChartView(View):
    def get(self, request, buyer_name, *args, **kwargs):
        try:
            buyer = Buyer.objects.get(user= User.objects.get(first_name=buyer_name))
            print(buyer)
            auctions = Auction.objects.all()
            prices = []
            months_price = []
            months = []
            for auction in auctions:
                price = auction.price_per_tonne
                months_price.append(auction.date)
                prices.append(price)
            sumprice = sum(prices)
            months = calenderutil.getAllMonthsStr()
            mean_price = sumprice/len(prices)
            context = {
                'prices':prices,
                'months_price':months_price,
                'months':months,
                'MeanPrice': round(mean_price, 3)
            }

            factories_traded = []
            amount = []
            amts = {}
            orders = Order.objects.filter(buyer=buyer)
            for order in orders:
                factory = order.employee.factory
                if factory not in factories_traded:
                    factories_traded.append(factory)
                if amts.get(factory.factory_name):
                    amts[factory.factory_name] = order.amount + amts[factory.factory_name]
                else:
                    amts[factory.factory_name] = order.amount 

            for x in range(len(factories_traded)):
                amount.append(amts.get(factories_traded[x].factory_name))

            context['factories'] = factories_traded
            print(amount)
            context['amounts'] = amount

            return render(request, 'buyer_charts.html', context)
        except:
            auctions = Auction.objects.all()
            prices = []
            months_price = []
            months = []
            for auction in auctions:
                price = auction.price_per_tonne
                months_price.append(auction.date)
                prices.append(price)
            sumprice = sum(prices)
            months = calenderutil.getAllMonthsStr()
            try:
                mean_price = sumprice / len(prices)
            except:
                mean_price = 0
            context = {
                'prices':prices,
                'months_price':months_price,
                'months':months,
                'MeanPrice': round(mean_price, 3)
            }

            return render(request,'buyer_charts.html', context)

class GetChartView(View):
    def get(self, request, factory_name):
        factory = SellerFactory.objects.get(factory_name=factory_name)

        class Stat:
            def __init__(self, data, year=2019):
                self.data = data
                self.year = year

        orders = Order.objects.all()
        data = {
            'jan':0,
            'feb':0,
            'mar':0,
            'apr':0,
            'may':0,
            'jun':0,
            'jul':0,
            'aug':0,
            'sep':0,
            'oct':0,
            'nov':0,
            'dec':0,
        }
        processed_orders = 0
        received = 0
        total_tonnes = 0
        tones_sold = 0

        auctions = Auction.objects.all()
        for auction in auctions:
            if auction.factory == factory:
                total_tonnes += auction.tonnes
                tones_sold += auction.tonnes - auction.tonnes_left

        for order in orders:
            if order.auction.factory == factory:
                if order.status == 2 or order.status == 3:
                    processed_orders +=1
                if order.auction.factory == factory:
                    received += 1
                if order.arrived:
                    if  order.date_placed.year == datetime.date.today().year:
                        if order.date_placed.month == 1:
                            data['jan'] += order.amount
                        elif order.date_placed.month == 2:
                            data['feb'] += order.amount
                        elif order.date_placed.month == 3:
                            data['mar'] += order.amount
                        elif order.date_placed.month == 4:
                            data['apr'] += order.amount
                        elif order.date_placed.month == 5:
                            data['may'] += order.amount
                        elif order.date_placed.month == 6:
                            data['jun'] += order.amount
                        elif order.date_placed.month == 7:
                            data['jul'] += order.amount
                        elif order.date_placed.month == 8:
                            data['aug'] += order.amount
                        elif order.date_placed.month == 9:
                            data['sep'] += order.amount
                        elif order.date_placed.month == 10:
                            data['oct'] += order.amount
                        elif order.date_placed.month == 12:
                            data['nov'] += order.amount
                        elif order.date_placed.month == 12:
                            data['dec'] += order.amount
        
        value_increase = 0
        if datetime.date.today().month == 1:
            val = data.get('jan')
            value_increase = val
        elif datetime.date.today().month == 2:
            val = data.get('feb')
            value_increase = val - data.get('jan')
        elif datetime.date.today().month == 3:
            val = data.get('mar')
            value_increase =  val-data.get('feb')
        elif datetime.date.today().month == 4:
            val = data.get('apr')
            value_increase =  val-data.get('mar')
        elif datetime.date.today().month == 5:
            val = data.get('may')
            value_increase =  val-data.get('apr')
        elif datetime.date.today().month == 6:
            val = data.get('jun')
            value_increase =  val-data.get('may')
        elif datetime.date.today().month == 7:
            val = data.get('jul')
            value_increase =  val-data.get('jun')
        elif datetime.date.today().month == 8:
            val = data.get('aug')
            value_increase =  val-data.get('jun')
        elif datetime.date.today().month == 9:
            val = data.get('sep')
            value_increase =  val-data.get('aug')
        elif datetime.date.today().month == 10:
            val = data.get('oct')
            value_increase =  val-data.get('sep')
        elif datetime.date.today().month == 12:
            val = data.get('nov')
            value_increase =  val-data.get('oct')
        elif datetime.date.today().month == 12:
            val = data.get('dec')
            value_increase =  val-data.get('nov')

        stat = Stat(data,datetime.date.today().year)
        context = {}
        context['stat'] = stat
        context['processed'] = processed_orders
        context['recieved'] = received
        context['total_tonnes'] = total_tonnes
        context['tonnes_sold'] = tones_sold

        if value_increase < 0:
            value_increase = str(value_increase)
        elif value_increase == 0:
            value_increase = str(value_increase)
        else:
            value_increase = "+"+str(value_increase)

        context['value_increase'] = value_increase
        
        percentage_sold = 0.00
        if total_tonnes !=0:
            percentage_sold = (tones_sold*100)/total_tonnes

        context['percentage_sold'] = round(percentage_sold,2)

        return render(request, "factory_charts.html",context)


class AcceptOrderView(View):
    def post(self, request, factory_id):
        id = request.POST.get("id")
        order = Order.objects.get(pk=id)
        order.status = 1
        chain = intergrator.ReadChainFromFile(id)
        chain.addTochain(order)
        order.order_valid = chain.CheckValidity()
        order.chain = chain.blockchain.getChainList()
        chain.DumpChain(id)
        myhasher = sha256(str(order.chain).encode("utf-8"))
        order.hash = myhasher.hexdigest()
        order.save()
        backup_utils.UpdateBackUpOrder(order)
        return HttpResponse("Successfully Updated")


class DeletAuction(View):
    def get(self,request, auction_id):
        print(auction_id)
        auction = Auction.objects.get(pk=auction_id)

transactions/templates/add_auction.html
{% extends 'base.html' %} {% block content %}
<script>
  showLoading()
</script>
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <div class="metric">
        <p class="orange">Create a New auction</p>
        <p>Please ensure all details, the information will be reviewed.</p>
      </div>
      {%if error%}
      <div class="dark-l panel-body">
        <h4 class="orange">An Error Occured</h4>
        <p>{{error}}</p>
      </div>
      {%endif%}
      <form method="POST" class="dark-l panel-body" action="{%url 'transactions:create_auction'%}">
        {% csrf_token %}
        <input type="hidden" name="factory" id="factory" value="{{user.sellerfactoryemployee.factory.pk}}">
        <input type="hidden" name="employee" id="employee" value="{{user.sellerfactoryemployee.pk}}">
        {%for field in form%}
        <div class="form-group">
          <label class="small">{{field.label}}</label><br>
          {{field}}
          {{field.helpText}}
        </div>
        {%endfor%}
        <button type="submit">Add to market</button>
      </form>
    </div>
    <!-- </form> -->
  </div>
</div>
</div>
{% endblock content %} {% block js %}
<script>
  // var auctionSocket = new WebSocket(
  //   "ws://" + window.location.host + "/ws/transactions/addauction/"
  // );
  // auctionSocket.onmessage = function(e) {
  //   console.log(JSON.parse(e.data));
  // };
  // auctionSocket.onclose = function(e) {
  //   console.log("chat socket disconnected unexpectedly");
  // };
  // document.querySelector("#submit_button").onclick = function(e) {
  //   var pricePerTonne = document.querySelector("#price_per_tonne").value;
  //   var dateHarvested = document.querySelector("#date_harvested").value;
  //   var amountInTonnes = document.querySelector("#amount_in_tonnes").value;
  //   auctionSocket.send(
  //     JSON.stringify({
  //       pricePerTonne: pricePerTonne,
  //       dateHarvested: dateHarvested,
  //       amountInTonnes: amountInTonnes
  //     })
  //   );
  // };
</script>
{% endblock js %}

transactions/templates/auction_history.html
{% extends 'base.html' %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="{% static 'toastr/toastr.min.css' %}">
{% endblock style %}
{% block content %} {% load static %}
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content dark">
        <div class="container-fluid">

            {%for auction in auctions%}

            <div class="dark-l">
                <div class="metric">
                    <h2>
                        Index no: {{auction.pk}}
                    </h2>
                    <hr>
                    {{auction.coffee_type}} <br>
                    {{auction.tonnes}} tonne{{auction.tonnes | pluralize}} <br>
                    Auctioned by {{auction.employee}} on {{auction.date}} <br>
                </div>
            </div>
            {%endfor%}

        </div>
    </div>
</div>
{%endblock content%}

transactions/templates/buy_bundle.html
{% extends 'base.html' %} {% block content %}
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <div class="metric">
        <div class="media">
          <div class="metric">
            <img style="width: 60px; height: 60px; margin-right:10px; float: left;"
              src="{{auction.factory.factory_logo.url}}" class="img-circle" />
            <div class="media-body">
              <h5 class="panel-title">
                <h3 style="margin: 0px">{{auction.factory.factory_name}}</h3>
                <br />
                {{auction.tonnes_left}} Tonnes left @
                <span>Tempreture {{auction.tempreture}} | Humidity {{auction.humidity}}%</span>
              </h5>
            </div>
          </div>

          <div class="form-group">
            <label for="amount">Amount in Tonnes</label>
            <input id="tonnes" type="number" class="form-control" aria-describedby="emailHelp" />
            <small id="amounthelp" class="form-text text-muted">Enter how many tonnes of coffee you want to buy from
              this
              bundle.</small>
          </div>
          <div class="form-group">
            <label for="date">Prefered Date of shipment</label>
            <input type="date" class="form-control" id="shipmentdate" aria-describedby="emailHelp" />
            <small id="datehelp" class="form-text text-muted">what is your prefered shipment date for the coffee</small>
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Confirm your account Password</label>
            <input id="password" type="password" class="form-control" id="exampleInputPassword1" />
          </div>
          <button id="placeorder" class="btn btn-primary">
            Place Order
          </button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %} {% block js %}
<script>
  var addOrderSocket = new WebSocket(
    "ws://" +
    window.location.host +
    "/ws/transactions/addorder/{{auction.employee.user.id}}/"
  );
  document.querySelector("#placeorder").onclick = function (e) {
    addOrderSocket.send(
      JSON.stringify({
        user: "{{auction.employee.pk}}",
        auction: "{{auction.id}}",
        shipmentdate: document.querySelector("#shipmentdate").value,
        tonnes: document.querySelector("#tonnes").value,
        password: document.querySelector("#password").value
      })
    );

    addOrderSocket.onmessage = function (e) {
      console.log(JSON.parse(e.data));
    };
    addOrderSocket.onclose = function (e) {
      console.log("the addOrderSocket socket closed unexpectedly");
    };
  };
</script>
{% endblock js %}

transactions/templates/buyer_charts.html
{%extends 'base.html'%}
{%load static%}
{%block content%}

<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <div class="panel-body dark-l">
                <div class="panel-body">
                    <h1 class="orange">Coffee Prices</h1>
                    <h3 class="white">${{MeanPrice}} Per Tonne</h3>
                    <p>Coffee prices in the market</p>
                    <canvas id="prices" height="100"></canvas>
                </div>
            </div>
            <br>
            <div class="panel-body dark-l">
                <div class="panel-body">
                    <h1 class="orange">{{value_increase}} Tonnes</h1>
                    <p>Showing Tonnes of coffee traded Per month</p>
                    <canvas id="myChart" height="100"></canvas>
                </div>
            </div><br>
            <div class="panel-body dark-l">
                <div class="panel-body">
                    <h1 class="orange">Factories Traded With</h1>
                    <canvas id="myChart2" height="80"></canvas>
                </div>
            </div>
            <script src="{%static 'node_modules/chart.js/dist/Chart.js'%}"></script>
            <script>
                months = []
                prices = []
                factories = []
                amounts = []
            </script>
            {%for month in months_price%}
            <script>
                included = false
                months.forEach(element =>
                {
                    if (element === "{{month}}")
                    {
                        included = true
                    }
                });
                if (!included)
                {

                    months.push("{{month}}")
                }
            </script>
            {%endfor%}
            {%for price in prices%}
            <script>
                prices.push("{{price}}")
            </script>
            {%endfor%}
            {%for factory in factories%}
            <script>
                factories.push("{{factory.factory_name}}")
            </script>
            {%endfor%}

            {%for amount in amounts%}
            <script>
                amounts.push("{{amount}}")
            </script>
            {%endfor%}
            <script>
                var ctx = document.getElementById('prices').getContext('2d');
                var myChart = new Chart(ctx, {
                    type: 'line',
                    data: {
                        labels: months,
                        datasets: [{
                            label: 'Price line in real time',
                            data: prices,
                            backgroundColor: [
                                'rgba(100,100,100,0.2)',
                            ],
                            borderColor: [
                                'rgba(226, 149, 6,1)'
                            ],
                            borderWidth: 3
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: false
                                }
                            }]
                        }
                    }
                });


                var ctx2 = document.getElementById('myChart').getContext('2d');
                var myChart = new Chart(ctx2, {
                    type: 'bar',
                    data: {
                        labels: factories,
                        datasets: [{
                            label: 'Factory trade deals',
                            data: amounts,
                            backgroundColor: [

                                'rgba(20,100,100,1)',
                                'rgba(50,10,60,1)',
                                'rgba(20,40,20,1)',
                                'rgba(200,20,100,1)'
                            ],
                            borderColor: [
                                'rgba(250, 0, 0, 1)'
                            ],
                            borderWidth: 1
                        }]
                    },
                    options: {
                        scales: {
                            yAxes: [{
                                ticks: {
                                    beginAtZero: true
                                }
                            }]
                        }
                    }
                });
            </script>
        </div>
    </div>
</div>

{%endblock content%}

transactions/templates/shipmentForm.html
{% extends "base.html" %}
{% block style %}
{% load static %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
<link rel="stylesheet" href="{% static 'chat/style.css' %}" />
{% endblock style %}
{% block content %}

<script>
  showLoading()
</script>
<div class="main">
    <!-- MAIN CONTENT -->
    <div class="main-content">
        <div class="container-fluid">
            <h3 class="no-margin no-padding">Shipment</h3>
            <div class="panel panel-body" style="background-color: rgb(205, 230, 236);">
                #{{order.id}} | Buyer: {{order.buyer}}<br>
                {%if order.chain_valid%}
                <span class="label-success label">Trusted Transaction</span><br>
                {%else%}
                <br><span class="label-error label>Order has been verified</span><br>
                {%endif%}

                units requested: {{order.amount}} tonne{{order.amount | pluralize}}<br><br>
                <span>Client expects Shipment by: </span><br><span class=" mx-sm-3">{{order.expected_date}}</span>
                <br><a href="#">Raise Issue</a>
            </div>
            <div class="panel panel-body">
                Enter Shipment information
                <br><small class="passwordHelpBlock">Enter valid shipment details. These Details will be
                    validated</small>
                <br>
                <br>
                <form action="{%url 'transactions:saveshipment'%}" method="POST">
                    {%csrf_token%}
                    <input type="hidden" name="id" id="id" value="{{order.pk}}">
                    {%for field in form%}
                    <div class="form-group">
                        {{field}}
                        {%if field.help_text%}
                        <small class="passwordHelpBlock">{{field.helpText}}</small>
                        {%endif%}
                    </div>
                    {%endfor%}
                    <button type="submit" class="btn btn-primary">Publish information</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

transactions/templates/view_factory.html
{% extends 'base.html' %} {% block content %} {% load static %}
<script>
  showLoading()
</script>
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <div class="metric">
            <img style="width: 60px; height: 60px; margin-right:10px; float: left;" src="{{factory.factory_logo.url}}"
              class="img-circle" />
            <div class="media-body">
              <h5 class="panel-title">
                <h3 style="margin: 0px"><b class="orange">{{factory.factory_name}}</b></h3>
                <br />
                Since {{factory.date_created}}<br />
                Altitude 20 |Temperature 30
              </h5>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="metric">
            <b>auction information</b>
            {% for auction in auctions%}
            <div class="dark-l panel-body">
              <span class="title orange">Ongoing Auction</span><br>
              <span>Auction No. {{auction.pk}}</span><br>
              <span>Tonnes {{auction.tonnes}}</span><br>
              <span>${{auction.price_per_tonne}} per tonne</span><br>
              <span>{{auction.coffee_type}}</span><br>
              <span>{{auction.tonnes_left}} tonne{{auction.tonnes_left|pluralize}} Left</span><br>
              <a href="{%url 'transactions:view_market' auction.pk%}">Buy Form this Auction</a>
            </div>
            {%endfor%}
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="metric">
            <h4><b class="orange">Legal documentation</b><br />
              {%if factory.trade_license%}
              <h3>Trade License</h3>
              <a href="{{factory.trade_license.url}}">Download Copy of license</a>
              <br><span>Content Validated</span>
              {%else%}
              <span>NO LICENSE</span>
              {%endif%}
          </div>
          <div class="metric">
            <h4><b class="orange">Factory Bio</b></h4>
            <p style="align-items: left;">
              <div>
                <span class="text">
                  {{factory.factory_bio}}
                </span>
              </div>
            </p>
          </div>
        </div>
        <div class="col-md-6">
          <div class="metric">
            {{factory.googlemap|safe}}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}