accounts/urls.py
from django.urls import path
from .views import homepage, profile, login, create_account, dashboard, GetFactoriesView, create_buyer_account, create_seller_account, logout

namespace = "accounts"

urlpatterns = [
    path("", homepage, name="homepage"),
    path("profile/", profile, name="profile"),
    path("login/", login, name="login"),
    path("dashboard/", dashboard, name="dashboard"),
    path("factories/", GetFactoriesView.as_view(), name="factories"),
    path('create_account/', create_account, name= "create_account"),
    path('create_buyer_account/', create_buyer_account, name = 'create_buyer_account'),
    path('create_seller_account/', create_seller_account, name = 'create_seller_account'),
    path("logout/", logout, name = "logout")
]

agriproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

namespace = "transactions"

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include(("accounts.urls", "accounts"), namespace="accounts")),
    path(
        "transactions/",
        include(("transactions.urls", "transactions"), namespace="transactions"),
    ),
    path("feedback/", include(("feedback.urls", "feedback"), namespace="feedback")),
    path("blog/", include(("blog.urls", "blog"), namespace = "blog")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import blog, blog_single

urlpatterns = [
    path('', blog , name = 'blog'),
    path('<int:id>/', blog_single, name = "blog_single")
]

transactions/urls.py
from django.urls import path
from .views import (
    add_auction,
    view_market,
    view_market_id,
    view_order,
    view_auction,
    chat,
    view_factory,
    AcceptOrderView,
    EnterShipmentInfoView,
    AddShipmentAddressView,
    GetChartView,
    confirmArival,
    DeletAuction,
    CreateAuction,
    GetBuyerChartView,
    ShowAuctionHistory,
    ShowTransactions,
)

namespace = "transactions"

urlpatterns = [
    path("add_auction/", add_auction, name="add_auction"),
    path("view_market/", view_market, name="view_market"),
    path("view_market/<int:id>/", view_market_id, name="view_market"),
    path("view_order/<int:order_id>/", view_order, name="view_order"),
    path("view_auction/", view_auction, name="view_auction"),
    path("chat/", chat, name="chat"),
    path(
        "view_market/view_factory/<int:factory_id>/", view_factory, name="view_factory"
    ),
    path(
        "view_order/<int:factory_id>/update_order/",
        AcceptOrderView.as_view(),
        name="accept_order",
    ),
    path(
        "shipmentinfo/<int:order_id>/",
        EnterShipmentInfoView.as_view(),
        name="shipmentview",
    ),
    path("ShipmentSaved/", EnterShipmentInfoView.as_view(), name="saveshipment"),
    path(
        "ShipmentAddress/",
        AddShipmentAddressView.as_view(),
        name="addshippmentaddress",
    ),
    path("charts/<str:factory_name>", GetChartView.as_view(), name="charts"),
    path("bcharts/<str:buyer_name>", GetBuyerChartView.as_view(), name="bcharts"),
    path("order-arrived/<int:order_id>", confirmArival, name="confirm"),
    path(
        "auction-remove/<int:auction_id>", DeletAuction.as_view(), name="delete-auction"
    ),
    path("create_auction/", CreateAuction.as_view(), name="create_auction"),
    path(
        "auction_history/<str:factory_name>/",
        ShowAuctionHistory.as_view(),
        name="auction_history",
    ),
    path("<str:factory_name>/", ShowTransactions.as_view(), name="showtransactions",),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>CoffeeAfrica|Online</title>
  <!-- chat stuff -->
  {% block style %} {% endblock style %}
  <!-- chat stuff -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
  <!-- VENDOR CSS -->

  <link rel="stylesheet" href="{% static 'toastr/toastr.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/mine.css'%}">
  <link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/vendor/linearicons/style.css' %}" />
  <link rel="stylesheet" href="{% static 'assets/vendor/chartist/css/chartist-custom.css' %}" />
  <!-- MAIN CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
  <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
  <!-- <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}" /> -->
  <!-- GOOGLE FONTS -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet" />
  <!-- ICONS -->
  <link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png" />
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicon.png' %}" />
</head>

<body>
  <!-- WRAPPER -->
  <div id="wrapper">
    <!-- NAVBAR -->
    {% include 'navbar.html' %} {% include 'sidebar.html' %}
    <!-- main content -->
    <div class="modal-transparent" id="loadingDiv">
      <div class="modal-content2">
        <span class="title">Loading please wait...</span>
        <img src="{%static 'assets/img/loading.gif'%}" alt="loading" height="100px">
      </div>
    </div>
    {% block content %}
    {% endblock content %}
    <!-- endmain -->
    <div class="clearfix"></div>
    <footer>
      <div class="container-fluid dark">
        <p class="copyright orange">
          Shared by <i class="fa fa-love"></i><a href="https://bootstrapthemes.co">BootstrapThemes</a>
        </p>
      </div>
    </footer>
  </div>
  <!-- END WRAPPER -->
  <!-- Javascript -->

  <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
  <script src="{% static 'assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js' %}"></script>
  <script src="{% static 'assets/vendor/chartist/js/chartist.min.js' %}"></script>
  <script src="{% static 'assets/scripts/klorofil-common.js' %}"></script>
  <script src="{% static 'assets/js/utils.js'%}"></script>
  {% block js %} {% endblock js %}
</body>

</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="fullscreen-bg">
  <head>
    <title>Login Coffee Africa</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"
    />
    <!-- VENDOR CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'assets/vendor/linearicons/style.css' %}"
    />
    <!-- MAIN CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
    <!-- FOR DEMO PURPOSES ONLY. You should remove this in your project -->
    <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}" />
    <!-- GOOGLE FONTS -->
    <link
      href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700"
      rel="stylesheet"
    />
    <!-- ICONS -->
    <link
      rel="apple-touch-icon"
      sizes="76x76"
      href="{% static 'assets/img/apple-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="96x96"
      href="{% static 'assets/img/favicon.png' %}"
    />
  </head>

  <body>
    <!-- WRAPPER -->
    <div id="wrapper">
      <div class="vertical-align-wrap">
        <div class="vertical-align-middle">
          <div class="auth-box ">
            <div class="left">
              <div class="content">
                <div class="header">
                  <p class="lead">Login to your account</p>
                  <div class="logo text-center">
                    <img
                      style="width: 200px; height: auto"
                      src="{% static 'custom_images/coffeeafricalogo.png' %}"
                      alt="Klorofil Logo"
                    />
                  </div>
                </div>
                <form class="form-auth-small" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="signin-email" class="control-label sr-only"
                      >Email</label
                    >
                    <input
                      type="email"
                      class="form-control"
                      id="signin-email"
                      placeholder="Email"
                      name="email"
                    />
                  </div>
                  <div class="form-group">
                    <label for="signin-password" class="control-label sr-only"
                      >Password</label
                    >
                    <input
                      type="password"
                      class="form-control"
                      id="signin-password"
                      placeholder="Password"
                      name="pass"
                    />
                  </div>
                  <div class="form-group clearfix">
                    <label class="fancy-checkbox element-left">
                      <input type="checkbox" />
                      <span>Remember me</span>
                    </label>
                  </div>
                  <button
                    type="submit"
                    class="btn btn-primary btn-lg btn-block"
                  >
                    LOGIN
                  </button>
                  <div class="bottom">
                    <span class="helper-text"
                      ><i class="fa fa-lock"></i>
                      <a href="#">Forgot password?</a></span
                    >
                  </div>
                </form>
              </div>
            </div>
            <div class="right">
              <div class="overlay"></div>
              <div class="content text">
                <h1 class="heading">
                  Welcome to our platform where you can trade coffee online
                </h1>
                <p>powered by blockchain</p>
              </div>
            </div>
            <!-- <div class="clearfix"></div> -->
          </div>
        </div>
      </div>
    </div>
    <!-- END WRAPPER -->
  </body>
</html>

templates/navbar.html
{% load static %}
<nav
  class="navbar navbar-default navbar-fixed-top"
  style="background-color: rgb(32, 30, 30);"
>
  <div class="brand orange" style="background-color: transparent;">
    <a class="title orange" href="{%url 'accounts:homepage'%}"
      >CoffeeAfrica.net</a
    >
  </div>
  <div class="container-fluid">
    <div class="navbar-btn">
      <button type="button" class="btn-toggle-fullwidth">
        <i class="lnr lnr-arrow-left-circle"></i>
      </button>
    </div>
    <form class="navbar-form navbar-left">
      <div class="input-group">
        <input
          type="text"
          value=""
          class="form-control"
          placeholder="Search dashboard..."
        />
        <span class="input-group-btn"
          ><button type="button" class="btn btn-primary">Go</button></span
        >
      </div>
    </form>

    <div id="navbar-menu">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
            <i class="lnr lnr-alarm"></i>
            <span class="badge bg-danger">{{notifycount}}</span>
          </a>
          <ul class="dropdown-menu notifications">
            {%for notification in notifications%}
            <li>
              <a
                href="/{{notification.app_name}}/{{notification.action}}/{{notification.id}}/"
                class="notification-item"
                ><span class="dot bg-success"></span>
                {{notification.message}}
              </a>
            </li>
            {%endfor%}
            <!-- <li>
              <a href="#" class="notification-item"><span class="dot bg-danger"></span>You have 9 unfinished
                tasks</a>
            </li>
            <li>
              <a href="#" class="notification-item"><span class="dot bg-success"></span>Monthly report is
                available</a>
            </li>
            <li>
              <a href="#" class="notification-item"><span class="dot bg-warning"></span>Weekly meeting in 1 hour</a>
            </li>
            <li>
              <a href="#" class="notification-item"><span class="dot bg-success"></span>Your request has been
                approved</a>
            </li> -->
            <li><a href="#" class="more">See all notifications</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            ><i class="lnr lnr-question-circle"></i>
            <span>Help</span>
            <i class="icon-submenu lnr lnr-chevron-down"></i
          ></a>
          <ul class="dropdown-menu">
            <li><a href="#">Basic Use</a></li>
            <li><a href="#">Working With Data</a></li>
            <li><a href="#">Security</a></li>
            <li><a href="#">Troubleshooting</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            ><img
              src="{% static 'assets/img/user.png' %}"
              class="img-circle"
              alt="Avatar"/>
            <span>{{user.username}}</span>
            <i class="icon-submenu lnr lnr-chevron-down"></i
          ></a>
          <ul class="dropdown-menu">
            <li>
              <a href="#"
                ><i class="lnr lnr-user"></i> <span>My Profile</span></a
              >
            </li>
            <li>
              <a href="#"
                ><i class="lnr lnr-envelope"></i> <span>Message</span></a
              >
            </li>
            <li>
              <a href="#"><i class="lnr lnr-cog"></i> <span>Settings</span></a>
            </li>
            <li>
              <a href="{% url 'accounts:logout' %}"
                ><i class="lnr lnr-exit"></i> <span>Logout</span></a
              >
            </li>
          </ul>
        </li>
        <!-- <li>
                        <a class="update-pro" href="https://www.themeineed.com/downloads/klorofil-pro-bootstrap-admin-dashboard-template/?utm_source=klorofil&utm_medium=template&utm_campaign=KlorofilPro" title="Upgrade to Pro" target="_blank"><i class="fa fa-rocket"></i> <span>UPGRADE TO PRO</span></a>
                    </li> -->
      </ul>
    </div>
  </div>
</nav>

templates/sidebar.html
{% load static %}
<!-- LEFT SIDEBAR -->
<div id="sidebar-nav" class="sidebar" style="background-color: rgb(48, 46, 46); padding-left: 2px; padding-right: 2px">
  <div class="dark-l">
    <div class="sidebar-scroll">
      <nav>
        <ul class="nav">
          <li style="margin-top: 2px;">
            <a href="/dashboard/" id="home">
              <i class=" lnr lnr-home"></i>
              <span>Dashbord</span>
            </a>
          </li>
          <li>
            {%if not user.sellerfactoryemployee.factory.factory_name%}
            <a href="{% url 'transactions:view_market' %}" id="market"><i class=" lnr lnr-code"></i>
              <span>Market</span></a>
            {%else%}
          <li>
            <a href="#subPages" data-toggle="collapse" class="collapsed"><i class="lnr lnr-file-empty"></i>
              <span>Auction</span>
              <i class="icon-submenu lnr lnr-chevron-left"></i></a>
            <div id="subPages" class="collapse ">
              <ul class="nav">
                <li><a href="{% url 'transactions:add_auction' %}" class="">Create a new Auction </a></li>
                <li><a href="{% url 'transactions:auction_history' user.sellerfactoryemployee.factory.factory_name%}" class="">View Auction History</a></li>
                <li><a href="page-lockscreen.html" class="">Manage Auction</a></li>
              </ul>
            </div>
          </li>
          {%endif%}
          </li>
          <li>
            {%if user.sellerfactoryemployee%}
            <a href="{%url 'transactions:charts' user.sellerfactoryemployee.factory.factory_name%}" id="charts"
              class=""><i class="lnr lnr-chart-bars"></i> <span>Charts</span></a>
            {%else%}
            <a href="{% url 'transactions:bcharts' user %}" id="charts"><i class="lnr lnr-chart-bars"></i>
              <span>Charts</span></a>
            {%endif%}
          </li>
          <script>
            document.getElementById('home').onclick = function ()
            {
              showLoading()
            }
            document.getElementById('charts').onclick = function ()
            {
              showLoading()
            }
            document.getElementById('market').onclick = function ()
            {
              showLoading()
            }
            document.getElementById('auction').onclick = function ()
            {
              showLoading()
            }
            if (document.URL.includes('dash'))
            {
              home = document.getElementById('home')
              home.classList.add('active')
            } else if (document.URL.includes('charts'))
            {
              charts = document.getElementById('charts')
              charts.classList.add('active')
            } else if (document.URL.includes('auction'))
            {
              auction = document.getElementById('auction')
              auction.classList.add('active')
            } else if (document.URL.includes('market'))
            {
              auction = document.getElementById('market')
              auction.classList.add('active')
            }
          </script>
          {%if user.sellerfactoryemployee.factory.factory_name%}
          <li>
            <a href="{%url 'transactions:showtransactions' user.sellerfactoryemployee.factory.factory_name%}" class=""><i class="lnr lnr-cog"></i> <span>Transactions</span></a>
          </li>
          {%else%}
          <li>
            <a href="{%url 'transactions:showtransactions' user%}" class=""><i class="lnr lnr-cog"></i> <span>Transactions</span></a>
          </li>
          {%endif%}
          <li>
            <a href="notifications.html" class=""><i class="lnr lnr-alarm"></i> <span>Notifications</span></a>
          </li>
          <li>
            <a href="tables.html" class=""><i class="lnr lnr-dice"></i> <span>Blog</span></a>
          </li>
          <li>
            <a href="icons.html" class=""><i class="lnr lnr-linearicons"></i> <span>Feedback</span></a>
          </li>
          <li>
            <a href="/" class=""><i class="lnr lnr-home"></i> <span>Home</span></a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>
<!-- END LEFT SIDEBAR -->